In [ ]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [ ]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 13
    else:
        return 0.33

In [ ]:
predict(dp1)

In [ ]:
predict(dp2)

In [ ]:
predict(dp3)

In [ ]:
predict(dp4)

In [ ]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']

In [ ]:
mlpredict(dp4)

In [ ]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'broken': 0}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'broken': 0}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'broken': 1}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'broken': 1}

In [ ]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 1
    else:
        return 0

In [ ]:
predict(dp1)

In [ ]:
predict(dp2)

In [ ]:
predict(dp3)

In [ ]:
predict(dp4)

In [ ]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))

In [ ]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return 1 if sigmoid(w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']) > 0.7 else 0

In [ ]:
mlpredict(dp4)

In [3]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [4]:
dp1

{'partno': 100,
 'maxtemp': 35,
 'mintemp': 35,
 'maxvibration': 12,
 'asperity': 0.32}

In [38]:
import numpy as np
#x0 = [v for k, v in dp1.items()]
#x5 = np.array([1] + [v for k, v in dp1.items()] [3:])
x1 = np.array([1] + [v for k, v in dp1.items()] [1:-1])
x2 = np.array([1] + [v for k, v in dp2.items()] [1:-1])
x3 = np.array([1] + [v for k, v in dp3.items()] [1:-1])
x4 = np.array([1] + [v for k, v in dp4.items()] [1:-1])

In [39]:
print(x0)
print(x5)

[100, 35, 35, 12, 0.32]
[ 1.   12.    0.32]


In [48]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [49]:
w_layer1 = np.random.rand(4)
w_layer1

array([0.98761607, 0.67793903, 0.51066096, 0.21388028])

In [50]:
#w_layer1 = np.random.rand(4)

def neuron(x):
    return sigmoid(x.dot(w_layer1))

In [51]:
neuron(x1)

1.0

In [42]:
#def sigmoid(x):
   # return 1/(1+np.exp(-x))

In [55]:
w_layer1 = np.random.rand(4,4)

def layer1(x):
    return sigmoid(x.dot(w_layer1))

In [57]:
w_layer1

array([[5.84372198e-01, 8.20770871e-01, 9.00009977e-01, 9.33584254e-01],
       [7.33969646e-01, 2.78073444e-01, 4.95396270e-01, 6.83662259e-01],
       [8.09221411e-01, 4.08576141e-01, 7.66833590e-01, 6.93726049e-01],
       [6.05208599e-01, 2.89088658e-01, 5.49504952e-01, 1.40522378e-04]])

In [58]:
neuron(x1)

array([1., 1., 1., 1.])

In [59]:
x = np.array([x1,x2,x3,x4])

In [60]:
x

array([[   1,   35,   35,   12],
       [   1,   46,   35,   21],
       [   1,   56,   46, 3412],
       [   1,   58,   48, 3542]])

In [61]:
layer1(x)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
w_layer2 = np.random.rand(4,4)

def layer2(x):
    return sigmoid(x.dot(w_layer2))

In [63]:
layer2(layer1(x))

array([[0.91080954, 0.88199893, 0.90300846, 0.84634741],
       [0.91080954, 0.88199893, 0.90300846, 0.84634741],
       [0.91080954, 0.88199893, 0.90300846, 0.84634741],
       [0.91080954, 0.88199893, 0.90300846, 0.84634741]])